version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo "Scanning for security vulnerability within dependencies"
      
  pre_build:
    commands:
      - echo "validating project"
      - mvn validate
  build:
    commands:
      - echo "Building project using maven"
      - mvn clean install -Dmaven.test.skip=true
  test:
    commands:
      - echo "Generating report"
      - mvn surefire-report:report
  post_build:
    commands:
      - echo "packaging completed on `date`"
      - mvn package

reports:
  'arn:aws:codebuild:ap-south-1:570813154045:report-group/testreport1':
  files:
    - './target/site/surefire-report.html'

artifacts:
  files:
    - target/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
